### ISSUE TITLE
List of versions disappeared in replay mode

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1003]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/wayback/20090520151032/http://www.geocities.com/hotsprings/

**Screenshots**

![dewfdwqfe](https://user-images.githubusercontent.com/25795364/88816790-b0474280-d1b4-11ea-82ac-68167bd7d3c5.JPG)

**Comment by igobranco** [comment]
The problem is the index cdxj of that specific page is returning http status 404.

Result of the call of the CDX API:
```
{"url": "http://www.geocities.com/hotsprings/", "timestamp": "20090520151032", "status": "404"}
```

Maybe this problem could be resolved re-indexing the Geocities collection.

**Comment by PedroG1515** [comment]
@igobranco 
Maybe you were looking at the arquivo.pt. 
However the collection is only in preprod.arquivo.pt, and I think it has nothing to do with the cdx, because How does an URL have a status code if it was not collected from live web?

**Comment by PedroG1515** [comment]
And at this moment it disappeared

![sfsaf](https://user-images.githubusercontent.com/25795364/89020734-4e531e00-d317-11ea-8453-8667b279e95f.JPG)

**Comment by igobranco** [comment]
No, I weren't talking about on the https://arquivo.pt but the https://preprod.arquivo.pt

This is the query to the cdx API that the browser do when you are view that page.
https://preprod.arquivo.pt/wayback/cdx?output=json&url=http%3A%2F%2Fwww.geocities.com%2Fhotsprings%2F&fields=url%2Ctimestamp%2Cstatus&filter=!~status%3A4%7C5&from=19960101&to=20200731

It returns nothing because the single record has a status 404. Search the only field without the status filter and to view all the information of that recourd.
https://preprod.arquivo.pt/wayback/cdx?output=json&url=http%3A%2F%2Fwww.geocities.com%2Fhotsprings%2F

The side panel isn't showing nothing, because it's suppose to show nothing when there isn't any record. 
I fixed this last night when I this ticket.

**Comment by PedroG1515** [comment]
Each has correct points. I get it.

A record cannot have a status code if it has not been collected from the live web. So, this problem cannot be from Geocities collection. And I am correct, because the "source": "$root:gigantic_index_1_v2.cdxj" is not geocities.cdxj.

However you are also correct, the only record is a 404, so there can be no problem with the interface.

We do not have any files inside of the "hotsprings" folder, only there are other directories within it (i.e., there is no html or other file type).

So everything is correct.
