### ISSUE TITLE
Wrong year on the left sidebar

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1046]
**What is the URL that originated the issue?**
https://arquivo.pt/wayback/20201024122709/http://www.inst-informatica.pt/cgi-bin/koha/opac-main.pl

**What happened?**
The correct year does not appear on the left sidebar.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/25795364/98652080-0343a080-2333-11eb-9ee7-06a4870bca87.JPG)

**Comment by igobranco** [comment]
Because that version is a 404.
If you remove the filter on the call to the CDXJ API you will see that version.

Link to CDXJ API: https://arquivo.pt/wayback/cdx?output=json&url=http%3A%2F%2Fwww.inst-informatica.pt%2Fcgi-bin%2Fkoha%2Fopac-main.pl&fields=url%2Ctimestamp%2Cstatus&from=19960101&to=20201110
```
....
{"url": "http://www.inst-informatica.pt/cgi-bin/koha/opac-main.pl", "timestamp": "20140930115713", "status": "302"}
{"url": "http://www.inst-informatica.pt/cgi-bin/koha/opac-main.pl", "timestamp": "20201024122709", "status": "404"}
```

**Comment by PedroG1515** [comment]
@igobranco
But if it's a 404, it should jump to version 20090926013206?

The user may be confused to see 2020 and on the left side there is 0 versions for 2020.
