### ISSUE TITLE
URLs with underscore

### ISSUE THREAD

**Issue by miguelwon** [arquivo/pwa-technologies#1064]
**What is the URL that originated the issue?**

https://arquivo.pt/noFrame/replay/20151014171253/http://www.dn.pt/opiniao.html

**What happened?**

I want to get the html of the original link. Why all the URLs within the generated html have all the hyphens replaced by underscore? 

```
import requests
from lxml import html
r = requests.get("https://arquivo.pt/noFrame/replay/20151014171253/http://www.dn.pt/opiniao.html")
webpage = html.fromstring(r.content)
urls = webpage.xpath('//a/@href')
```

check for example `urls[19]`:
`/noFrame/replay/20151014171253/http://www.dn.pt/opiniao/editoriais/interior/costa_atomico_4832802.html
`
that should be:

`/noFrame/replay/20151014171253/http://www.dn.pt/opiniao/editoriais/interior/costa-atomico-4832802.html
`

**Comment by amourao** [comment]
Hello Miguel,

the url hyphen replacement is performed by the replay software.
If you want to get the true original HTML file, you must add `id_` after the timestamp.

https://arquivo.pt/noFrame/replay/20151014171253id_/http://www.dn.pt/opiniao.html

Does this solve your problem?

**Comment by amourao** [comment]
It looks like the issue is in how DN is rewriting the URLs:

https://arquivo.pt/wayback/20151020185740/http://www.dn.pt/opiniao/editoriais/interior/costa_atomico_4832802.html
https://arquivo.pt/wayback/20151020185740/http://www.dn.pt/opiniao/editoriais/interior/costa-atomico-4832802.html

are both redirected to the hyphenated version.
As we collected links the way DN provided them at the time, there isn't any specific issue on our side,
