### ISSUE TITLE
Citation Saver: Create a web service to save all URLs from a PDF (uploaded)

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1147]
Arquivo.pt will extract all links referenced in the books and crawl in high-quality using Brozzler so that the content of citations may prevail accessible for future access.

Steps:

- [x] #1163 Create Mockups of the page to Save URLs from PDF (create a page on Arquivo.pt vs Sobre.arquivo.pt?). For instance, https://preprod.sobre.arquivo.pt/pt/save-links-pdf/ (The plugin to upload PDFs has limitations of the space).
- [x] #1176
- [x] Decide the best extractor of URLs from PDFs. (Check the Google Doc "Procedimento PDF to URL" from Arquivo.pt Google Drive;
- [x] Implement data workflow;
- [x] @dcgomes reviews the text presented on the UI;
- [x] Create regression tests
- [x] Create monitoring on Uptime robot
- [x] Install GAnalytics 4
- [ ] Talk to Michael Nelson, Klein, and Von Sompel (Memento crew) about the idea.

**Comment by dcgomes** [comment]
- Add field on the form to input URL to get the PDF from an  online location.
- Test service with these PDFS (open access books):
- https://www.cambridge.org/core/services/aop-cambridge-core/content/view/3F8D7BA2C0FE3A7126A4D9B73A89415D/9781108429092AR.pdf/Stand_out_of_our_Light.pdf?event-type=FTLA
- https://tictank.pt/biblioteca/ (several books)

**Comment by dcgomes** [comment]
Use the following texts:

### EN

CitationSaver Preserves citations to online resources

Documents cite online content that quickly disappear.

CitationSaver preserves the content of cited links (e.g. web pages cited in a book) so that they can be later recovered from Arquivo.pt.

Submit a document and CitationSaver will preserve its cited links:

Insert the URL to the document:

Accepted formats: PDF, TXT. Max size: 100 MB
Your email (optional):

Save cited links (button)

**Update page <title> and meta description to "CitationSaver: preserves citations to online resources" **

### PT

CitationSaver Preserva citações para recursos online

Os documentos citam conteúdos online que desaparecem rapidamente.

O CitationSaver preserva o conteúdo das ligações citadas (ex. páginas web citadas num livro) para que possam ser recuperadas mais tarde a partir do Arquivo.pt.

Submeta um documento e o CitationSaver preservará as ligações nele citadas:

Insira o URL do documento:

Formatos aceites: PDF, TXT. Tamanho máximo: 100 MB
O seu e-mail (opcional):

Guardar ligações citadas (botão)

**Atualizar página <título> e meta descrição para "CitationSaver: preserva citações para recursos online" **

**Comment by dcgomes** [comment]
- O espaçamento entre parágrafos tem de ser maior do que entre linhas:
![image](https://user-images.githubusercontent.com/13120352/207860466-b65694f7-63a9-4bad-b66c-487a00433174.png)

- Trocar "Link" por "URL"
![image](https://user-images.githubusercontent.com/13120352/207860584-f2e61930-9fd8-43c2-acd3-37fe90c65fdd.png)

-  Colocar labels em PT para "Browse" e "No file selected": 
![image](https://user-images.githubusercontent.com/13120352/207860715-ada448de-3654-44db-b18e-c952c94b24df.png)

- Mudar "Inserir" para "Insira":
![image](https://user-images.githubusercontent.com/13120352/207860791-7abb9d5d-7fce-4791-a7fe-d966901eca4e.png)
