### ISSUE TITLE
Mockups CitationSaver to HTML/CSS

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#1176]
https://www.figma.com/file/EUZUVc3IP5kFzIDW00rYtO/Citation-Saver?node-id=0%3A1

**Comment by VascoRatoFCCN** [comment]
Working prototype on https://dev.arquivo.pt/services/citationsaver

**Comment by VascoRatoFCCN** [comment]
Replace text with:

PT - “CitationSaver - Preserva citações para recursos online
Os documentos citam recursos online que rapidamente desaparecem.
O serviço CitationSaver permite preservar estes recursos arquivando-os no Arquivo.pt (ex. referências a páginas web num livro).”
EN - “CitationSaver - Preserves citations to online resources
Documents cite online content that quickly disappears.
CitationSaver preserves the content of cited resources so that they can be later recovered from Arquivo.pt (e.g. references to web pages cited in a book).”
