### ISSUE TITLE
Change position of the embargo message when Searching By url in the column 'more results'

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#156]
When searching for all the versions for a given url, e.g http://arquivo.pt/search.jsp?l=pt&query=sapo.pt&btnSubmit=Pesquisar in the last column the text of More Results the embargo period message 'Atualizações mais recentes que 1 ano serão disponibilizadas futuramente.
saiba porquê' should be at the top of the column and not at the bottom.

**Comment by hmendes** [comment]
The issue is not CSS, but with the table structure instead.

Here goes a suggestion to try.

In <table> with the class name "tabela-principal":
1. We need to move that <td> to the first <tr> group (after <tbody>)
2. So, move the <td> with the class name "mais-resultados", considering the column order.
3. Then, apply the property rowspan="99".

**Comment by Fernando-Melo** [comment]
already done in Janus
