### ISSUE TITLE
Nutchwax: Resource Not Found

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#164]
Some resources are not being returned by nutchwax although they exist. Such is the case of the following url:
https://www.healthy-workplaces.eu/en/campaign-partners/official-campaign-partners/eorna/@@images/8a76b22f-f7eb-4e3a-bc8a-40d28d3f505d.jpeg

It is possible to confirm that the resource is not returned by nutchwax by using the opensearch API:
http://p41.arquivo.pt/nutchwax/opensearch?query=closestdate%3A20141121162807+exacturlexpand%3Ahttp://www.healthy-workplaces.eu/en/campaign-partners/official-campaign-partners/eorna/@@images/8a76b22f-f7eb-4e3a-bc8a-40d28d3f505d.jpeg&hitsPerPage=10000&start=0&dedupField=site&hitsPerDup=10000&hitsPerSite=10000&waybackQuery=true

The image exists and is correctly stored in the arc file. The image is indexed properly when using cdx, but not found using nutchwax indexes

**Comment by FCCNhviana** [comment]
It was taken the approach of indexing only the ArcFile which contains the web content mentioned above and inspect if the web content was indexed. The following are information about the Arc.
* Details about the web content:
* Collection name: EAWP6 (.eu)
* Arc file name: IAH-20141122224919-09396-p12.arquivo.pt.arc.gz
* Arcoffset: 83737965
The ArcFile was deployed. After the analysis through Luke and a development environment (i.e. Arquivo.pt with only the ArcFile with problems) , it was concluded that there are problems on the indexation because it was not available on the searching system. Hence,  the hadoop job, which provides indexation, had problems when indexing this web content, and there was no logged information about.

**Comment by Fernando-Melo** [comment]
Remove Janus milestone, since this issue requires a considerable amount of effort? (we need to fix problems with the indexing script, or adopt CDX )

**Comment by FCCNhviana** [comment]
This issue might require migration of our Hadoop-job for indexing to a new version which means a lot of effort (our Hadoop-job only compile with Java 6). However, when the migration to SOLR is completed we have to reproduce it again.

**Comment by dcgomes** [comment]
PyWB finds the image:
http://arquivo.pt/wayback/20141122230343/https://www.healthy-workplaces.eu/en/campaign-partners/official-campaign-partners/eorna/@@images/8a76b22f-f7eb-4e3a-bc8a-40d28d3f505d.jpeg

**Comment by danielbicho** [comment]
This is not a problem anymore, the text indexing do not need to find this image.
