### ISSUE TITLE
Not Found Html Page

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#203]
1) Search if the not found URL is a live Web Page, in that case show a suggestion to archive that Webpage;

2) Check if there is a memento for the requested URL, in that case show a suggestion to look for the resource in other archives.

**Comment by Fernando-Melo** [comment]
Done

**Comment by dcgomes** [comment]
http://arquivo.pt/search.jsp?l=pt&query=http%3A%2F%2Fwejkfwelfwe.pt&btnSubmit=Pesquisar

I think that on the search results page should we also link to the Memento Time Travel portal instead of the IA.

Verifique o URL
Sugira a página para que seja arquivada.
- "Pesquise no Internet Archive." -> REMOVE
- "Pesquise outros arquivos web." change to "Pesquise noutros arquivos" 
For terminology consistency with the ReplayBar.

Same for EN version.

**Comment by Fernando-Melo** [comment]
Done in p27
