### ISSUE TITLE
Hour in archive date appears twice and miss-aligned

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#208]
On version Abril 21 07:09, the 07:09 appears twice
http://arquivo.pt/wayback/20150421070927/http://observador.pt/topico/ataque-ao-charlie-hebdo/
Verify if there are two versions archived at 07:09.

The chosen hour should appear be aligned to the hour above.

Another similar case: 
http://arquivo.pt/wayback/20091015033801/http://www.popnews.com/popnews/holden2/
03:38 and 03:39 should be vertically aligned.

**Comment by Fernando-Melo** [comment]
Regarding the 2 versions with the same hours and minutes, this is the expected result.
Since we dont distinguish between 
http://observador.pt/topico/ataque-ao-charlie-hebdo/   (notice the slash at the end) and
http://observador.pt/topico/ataque-ao-charlie-hebdo

In that particular case we got two versions at the same time.

**Comment by Fernando-Melo** [comment]
Regarding the vertical alignment, I think it is intentional.
Bruno Monteiro made the css in a way that the date that is currently selected is a little bit more to the right, I think it is to give more focus to the selected version

**Comment by dcgomes** [comment]
Remove italic and put bold.

**Comment by Fernando-Melo** [comment]
done in p27
