### ISSUE TITLE
Advanced Query ignores phrase search restriction

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#214]
Advanced Query ignores phrase search restriction.

For instance,
http://arquivo.pt/search.jsp?l=en&btnSubmitTop=Search&adv_and=ataque&adv_phr=je+suis+charlie&adv_not=&dateStart=01%2F01%2F2015&dateEnd=31%2F12%2F2015&sort=old&format=all&site=&hitsPerPage=10

The Result http://arquivo.pt/wayback/20150106184813/http://www.rtp.pt/noticias/index.php does not contain the phrase "je+suis+charlie"

Looks like a redirect problem.

**Comment by Fernando-Melo** [comment]
The problem is very interesting. 

When you check the above query. The first result is pointing to the following link:

http://arquivo.pt/wayback/20150107060305/http://www.rtp.pt/noticias/

Notice the date that is pointing to:  2015 01 07 at 06:03:05

**Comment by Fernando-Melo** [comment]
But when you go to the Wayback and search for the archived version of that Website, at the 7th of July you see the following date:

http://arquivo.pt/wayback/20150107180305/http://www.rtp.pt/noticias/

Notice that the date is very similar to the one in my above comment: 2015 01 07 at 18:03:05

**Comment by Fernando-Melo** [comment]
The problem is one of the following 2)

1) There are some bugs in our indexing scripts that are linking the titles to wrong timestamps (in the above example it is pointing to 06 instead of 18h) - This is the most probable problem

2) Some bug in Nutchwax returning Wrong timestamps (18h when it should be 06h)

Either Way I will confirm it by looking at the arc record

**Comment by Fernando-Melo** [comment]
It was a small bug in search-result-component.jsp which was converting the hours to 0-12 format instead of 0-24 in full-text searches.
