### ISSUE TITLE
Several tests aren't being run

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#25]
Originally reported on Google Code with ID 26

```
Due to several tests classes not respecting the standard layout expected by Maven, serveral
Junit test classes aren't being run.

Tests by convention need to be in the folder: {project.home}/src/test/*


The test classes that I identified with this problem are:

PwaArchive-Access folder:
-------------------------
projects/nutchwax/nutchwax-thirdparty/nutch/src/plugin/parse-msword/src/java/org/apache/nutch/parse/msword/Test.java
projects/nutchwax/nutchwax-core/src/main/java/org/archive/access/nutch/NutchwaxTest.java

PwaSpellchecker folder:
-----------------------
src/main/java/pt/arquivo/spellchecker/tests/TestSpellChecker.java

PwaLucene folder:
-----------------
src/main/java/org/apache/lucene/pruning/TestPruningReader.java
src/main/java/org/apache/lucene/search/tests/PwaSpanVersionsTest.java
src/main/java/org/apache/lucene/search/tests/PwaLinInlinksTest.java
src/main/java/org/apache/lucene/search/tests/PwaBoostNewerTest.java
src/main/java/org/apache/lucene/search/tests/PwaBoostNewerAndOlderTest.java
src/main/java/org/apache/lucene/search/tests/PwaTFxIDFTest.java
src/main/java/org/apache/lucene/search/tests/PwaUrlDepthTest.java
src/main/java/org/apache/lucene/search/tests/PwaMinSpanTest.java
src/main/java/org/apache/lucene/search/tests/PwaLinPagerankTest.java
src/main/java/org/apache/lucene/search/tests/PwaBoostOlderTest.java
src/main/java/org/apache/lucene/search/tests/PwaBM25Test.java
src/main/java/org/apache/lucene/search/tests/PwaDateDistributionSearchTest.java
src/main/java/org/apache/lucene/search/tests/PwaUrlSlashesTest.java
src/main/java/org/apache/lucene/search/tests/PwaSearchTest.java
src/main/java/org/apache/lucene/search/tests/PwaLuceneSimilarityTest.java
src/main/java/org/apache/lucene/search/tests/PwaNumberVersionsTest.java
```

Reported by `devel.david@vcruz.net` on 2012-02-15 11:54:24
- **Blocked on**: #23

**Comment by dcgomes** [comment]
@FCCNhviana check if problem persists?

**Comment by danielbicho** [comment]
The test folder layout is not respecting the layout that maven expects. The more important tests are Lucene and they can be enabled changing the default Source Directory for tests with the following maven pom directive:

<testSourceDirectory>src/main/java/org/apache/lucene/search/tests/</testSourceDirectory>

Also some the Lucene package have to be refactor, because some packages have no existent references.

For instance, there is no more a package called org.apache.lucene.search.rankers.queryindependent, instead there is a org.apache.lucene.search.features.queryindependent.

The tests to run also need some test collection on the build machine, and they should be enabled.

I had fixed this to pass but it need to be tested. I will downgrade the impact of this issue for low and not include in Hercules milestone since no development is being made on this code and higher priority issues need to be solved first.

**Comment by jnobre** [comment]
`projects/nutchwax/nutchwax-thirdparty/nutch/src/plugin/parse-msword/src/java/org/apache/nutch/parse/msword/Test.java ` : It is a standalone class. It isn't a unit test (junit), it is a class standalone Java call test. Which served as tests on development.

` src/main/java/pt/arquivo/spellchecker/tests/TestSpellChecker.java`: The Spellchecker test is not updated, it is not to run. A new selenium test is needed.

The tests related to PwaLucene are tests performed by Miguel Costa, to evaluate the ranking, it does not make sense to integrate these tests into the quality control flow of the code.
