### ISSUE TITLE
some URLs are not working in syntax wayback/*/url

### ISSUE THREAD

**Issue by Fernando-Melo** [arquivo/pwa-technologies#386]
How to reproduce the issue:
1) open [http://arquivo.pt/wayback/*/http://ultimahora.publico.pt/shownews.asp?id=1163919&idCanal=31](http://arquivo.pt/wayback/*/http://ultimahora.publico.pt/shownews.asp?id=1163919&idCanal=31)

2) Notice that the parameter idCanal=31 disappeared

**Comment by Fernando-Melo** [comment]
Possible solutions:
1) Query.html in Pywb with similar behaviour as nutchwax's search.jsp (move code from nutchwax to pywb)
2) Redirect Httpd with parameters: arquivo.pt/wayback/*/url?param1&param2 should redirect to arquivo.pt/search.jsp?query=url%3Fparam1%26param2
3)  Backend redirect in python.

**Comment by igobranco** [comment]
https://bz.apache.org/bugzilla/show_bug.cgi?id=49746

**Comment by igobranco** [comment]
On release deploy needs an update of apache httpd configuration.

**Comment by dcgomes** [comment]
The problem is back again due to the pywb type modifiers such as "mp_":

https://arquivo.pt/wayback/20201204230751mp_/https://www.fct.pt/noticias/index.phtml.pt?id=595&/2020/10/Concurso_AI_4_COVID-19_selecionou_12_projetos

However the character "?" are properly handled for conventional wayback URLs:
https://arquivo.pt/wayback/20201204230751/https://www.fct.pt/noticias/index.phtml.pt?id=595&/2020/10/Concurso_AI_4_COVID-19_selecionou_12_projetos

This problem impacts complementary services such as arquivo404:
https://www.fct.pt/noticias/index.phtml.pt?id=595&/2020/10/Concurso_AI_4_COVID-19_selecionou_12_projetos

Related to #192

**Comment by dcgomes** [comment]
Seems to be fixed.
