### ISSUE TITLE
Add collection search parameter on API

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#416]
Add search parameter collection to enable users to restrict search to one or several crawls, such as daily crawls of online publications (FAWP).

We must publish descriptions of the crawls and the assigned collection identifier.

As first step, we can reference the documentation published at our Internet Archive collections page (https://archive.org/details/portuguese-web-archive) and cite the field "pwacrawlid" (e.g. AWP19) as the collection identifier.

**Comment by Fernando-Melo** [comment]
related to #389

**Comment by igobranco** [comment]
The full text search API already support the collection parameter.

**Comment by igobranco** [comment]
Nevertheless it isn't supported on image search API, so I'm reopening this issue.

**Comment by Fernando-Melo** [comment]
Add a collection parameter in Imagesearch API
in the request user adds a parameter collection=FAWP23
in the SOLR call we need to add to the fqStrings  collection:FAWP23

**Comment by igobranco** [comment]
I've added the collection parameter to Image Search API.

To make it working for the normal arquivo.pt users, it's need that image search screens on nutchwax-mobile parse the collection parameter as a special one and send it as image search API parameter instead of sending it on query (q) parameter. 

Instead of:
https://arquivo.pt/imagesearch?q=sapo+collection%3ARoteiro

Execute:
https://arquivo.pt/imagesearch?q=sapo&collection=Roteiro

**Comment by igobranco** [comment]
Now the user interface support collection parameter.
