### ISSUE TITLE
Database insert time

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#49]
Originally reported on Google Code with ID 50

```
To process the multiple urls collections, there is a need to have a database with urls.
In the creation of this database there is a trigger and for every insert we verify
if the url and date is repeated. This is very inefficient, for every insert verifying
if there are repetitions. 

This part of the process should be done in a different part, not the database.
```

Reported by `simaofontes` on 2012-08-30 14:11:49

**Comment by danielbicho** [comment]
This method to insert database URLs when indexing FAWPs lead us to several problems. 

Last year, this problem caused the server hang while indexing, because a cronjob launched each 5 minutes could not complete, with time, more and more hanging cronjobs are launched and the server hangs. This was solved not launching that cronjob.

Some problems still arise, while indexing FAWPS, the server cannot report monitoring metrics to nagios leading to UNKNOW STATES alerts. The IO utilization ratio reach 100%.

There is no need to use this inefficient trigger if the table uses as PRIMARY KEY a composite index of url + date fields.

I see that the trigger creating code as been commented out, and the table is created with a composite index. BUT the trigger still exist in database...

```
indexing=> \df before_insert
                        List of functions
 Schema |     Name      | Result data type | Argument data types 
--------+---------------+------------------+---------------------
 public | before_insert | "trigger"

```
This verification dont make sense, and is putting a great overhead at the server.

**Comment by danielbicho** [comment]
This problem does not happen any more on the new server. Also, the trigger is needed for postgres command line inserting using the CSV (so it not break). Not the best way, but for now it works.
