### ISSUE TITLE
Patching no Arquivo.pt ou Completar página - doesn't seem to be working

### ISSUE THREAD

**Issue by ricardobasiliopt** [arquivo/pwa-technologies#665]
I put a URL - https://preprod.arquivo.pt/wayback/20081021233540/http://www.ojogo.pt/
On my pc the interface changed to the mobile version: https://m.preprod.arquivo.pt/noFrame/patching/record/20081021233540/http://www.ojogo.pt/
Then I clicked on "Completar página".  Nothing happened. 
But on Internet Archive the closest date of this version has more contents: https://web.archive.org/web/20081021233540/http://www.ojogo.pt/
So, "Completar página" didn´t work.

**Comment by danielbicho** [comment]
It is a problem with the replay of the page. Pywb has problems rendering this page. 
Patching doesn't do anything because we already have the resources (our version was donated by Internet Archive)

Internet Archive has its own wayback solution.

Result of using our pywb with only resources from Internet Archive result: (through memento)
![image](https://user-images.githubusercontent.com/13105310/70813992-6eeb5980-1dc2-11ea-8988-e51d43bd0afc.png)

Internet Archive version:
![image](https://user-images.githubusercontent.com/13105310/70814016-832f5680-1dc2-11ea-8b34-acef5707844d.png)
