### ISSUE TITLE
After deploy 2018 collections some sites doesn't have any version

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#722]
**What is the URL that originated the issue?**
Search the URL https://www.publico.pt on arquivo.pt.
https://arquivo.pt/search.jsp?l=pt&query=https%3A%2F%2Fwww.publico.pt&btnSubmit=Pesquisar&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2019

**What happened?**
It isn't showing any 2018 year version for publico.pt URL.

**What should have happened?**
Show each daily version of the publico.pt site, but for fccn.pt and sapo.pt is working fine.

**Screenshots**
For publico.pt:
![image](https://user-images.githubusercontent.com/67018/72148472-cddbc880-3398-11ea-976f-7094bd6e4489.png)

For fccn.pt:
![image](https://user-images.githubusercontent.com/67018/72148496-e350f280-3398-11ea-95b5-7fae8ee7a825.png)

**Comment by igobranco** [comment]
Examples working:
```bash
[root@p85 indexes_cdx]# /opt/sgrep-1.0/sgrep "pt,sapo)/ " FAWP32Sorted.cdxj FAWP33Sorted.cdxj  FAWP34Sorted.cdxj  FAWP35Sorted.cdxj | wc -l
1157
```

Example not working:
```bash
[root@p85 indexes_cdx]# /opt/sgrep-1.0/sgrep "pt,observador)/ " FAWP32Sorted.cdxj FAWP33Sorted.cdxj  FAWP34Sorted.cdxj  FAWP35Sorted.cdxj | wc -l
0
```

But specific sub page works fine - https://www.publico.pt/2018/05/01/economia/noticia/manuel-pinho-e-os-contratos-que-deram-2500-milhoes-a-edp-em-dez-anos-1815883:
```bash
[root@p85 indexes_cdx]# /opt/sgrep-1.0/sgrep "pt,publico)/" FAWP32Sorted.cdxj FAWP33Sorted.cdxj  FAWP34Sorted.cdxj  FAWP35Sorted.cdxj | grep "https://www.publico.pt/2018/05/01/economia/noticia/manuel-pinho-e-os-contratos-que-deram-2500-milhoes-a-edp-em-dez-anos-1815883"
FAWP33Sorted.cdxj:pt,publico)/2018/05/01/economia/noticia/manuel-pinho-e-os-contratos-que-deram-2500-milhoes-a-edp-em-dez-anos-1815883 20180604172238 {"url": "https://www.publico.pt/2018/05/01/economia/noticia/manuel-pinho-e-os-contratos-que-deram-2500-milhoes-a-edp-em-dez-anos-1815883", "mime": "text/html", "status": "200", "digest": "GTGB73U6EXDPH46CH2L75KQ25XHIL3AC", "length": "89347", "offset": "37690821", "filename": "IAH-20180604172205656-p84.arquivo.pt.arc.gz"}	
```

**Comment by amourao** [comment]
I've checked for a couple of pages that I've used on revisionista, and here are some findings regarding which captures are missing

It looks like the problem is clustered around Jun 30/Jul 1 and Sep 30/Oct 1, although there are missing captures for the full 2018 period.

publico.pt: no 2018 captures
shifter.sapo.pt/shifter.pt: no 2018 captures
observador.pt: almost no captures
sicnoticias.pt: almost no captures
visao.sapo.pt: missing starting Jul 1
cmjornal.pt: missing starting Jul 1
dnoticias.pt: missing starting Jul 1
dn.pt: missing starting Jul 1
tvi24.iol.pt: missing starting Jul 1
tvi24.iol.pt: missing starting Jul 1
jornaleconomico.sapo.pt: missing from Jul 1 to Oct 1
rtp.pt: missing from Jul 1 to Oct 1
sol.sapo.pt: missing parts of Apr, May and Jun

jornaldenegocios.pt: looks ok
sapo.pt: looks ok
jn.pt: looks ok

**Comment by danielbicho** [comment]
Be extra careful using the sorted grep, since the tool doesn't detect the underline problem that is the file not being sorted as sgrep expects it to be.

Cdxj indexes were sorted with LC_ALL=C, and are now working
