### ISSUE TITLE
"Collection" field does not appear on the Technical Details

### ISSUE THREAD

**Issue by dcgomes** [arquivo/pwa-technologies#770]
**What is the URL that originated the issue?**

"collection" EAWP19 does not appear on the Technical Details.
https://m.arquivo.pt/wayback/20180529044325/http://israblog.nana10.co.il/blogread.asp?blog=811367

But it appears on the following version:
https://arquivo.pt/wayback/20180917061507/http://israblog.nana10.co.il/blogread.asp?blog=811367

**Comment by danielbicho** [comment]
This was indexed as AWP profile collection, as it should be, but somehow H3 captured the same URL two times. Therefore, on the FTS it's only keeping the last version (201809).

Analyzing the H3 job, I can see that there was a crawl relaunch and an attempt to recover the frontier state. I say attempt because, the frontier log should be marked as processed and weirdly is not.

We need to check how much duplication there is in this collection. Although right now indexing with a fawp profile is not a solution because of the collection parameter problem.

**Comment by igobranco** [comment]
Another approach is to add the collection on cdxj records and on wayback template we already know the collection before calling the http://arquivo.pt/textsearch?metadata=... 
Maybe in future we can add this extra field to better detect errors. #788

**Comment by danielbicho** [comment]
Will be solved with #846

**Comment by danielbicho** [comment]
ready for when EAWP19.cdxj has the collection attribute
