### ISSUE TITLE
Missing images from EAWP19 collection

### ISSUE THREAD

**Issue by amourao** [arquivo/pwa-technologies#774]
**What is the URL that originated the issue?**
https://arquivo.pt/images.jsp?l=en&size=all&type=&tools=off&safeSearch=on&query=collection%3AEAWP19&btnSubmit=Search&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2019

**What happened?**
Second and third images are not being returned,
https://arquivo.pt/wayback/20181104022403im_/http://f.nanafiles.co.il/upload/Xternal/IsraBlog/97/91/74/749197/posts/23067895.jpg
https://arquivo.pt/wayback/20181104022406im_/http://f.nanafiles.co.il/upload/Xternal/IsraBlog/97/91/74/749197/posts/23067845.jpg

but they show up in the CDX index
https://arquivo.pt/wayback/cdx?url=http://f.nanafiles.co.il/upload/Xternal/IsraBlog/97/91/74/749197/posts/23067845.jpg

**What should have happened?**
Images should appear

**Screenshots**

**Comment by Eversong** [comment]
An error is being throw due to an encoding error. The records have an invalid character being served on the HTTP headers. This case is a Trademark character lol...

 A patch to catch the expection and remove this invalid header solves the problem. But I need to generalize the solution so it could be accepted upstream

**Comment by PedroG1515** [comment]
Fixed
