### ISSUE TITLE
OpenSearch and PWA results are not the same.

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#78]
Originally reported on Google Code with ID 79
```
There is a problem with the queries produced by the PWA and OpenSearch. One suppose
that the way that the queries are done are not the same.

The debug guidelines that have been done, so far are the following.

http://p58.arquivo.pt/search.jsp?l=pt&query=http%3A%2F%2Fwww.sapo.pt%2Findex.html&btnSubmit=Pesquisar+no+Arquivo&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2013
http://p62.arquivo.pt/opensearch?query=http://www.sapo.pt/index.html

The two examples above produce different results. Its suspected that there is nothing
to do with the Expand Urls feature provided by PWA. Besides, the link http://www.sapo.pt/index.html
was queried in the two forms and the return page did not matched.

```

Reported by `HugoHAViana` on 2014-10-21 12:51:57

**Comment by dcgomes** [comment]
It must be documented why the issue was reopened.

Describe problem and present illustrative examples.


On 13-10-2015 10:41, Fernando-Melo wrote:
> Reopened #78 <https://github.com/arquivo/pwa-technologies/issues/78>.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arquivo/pwa-technologies/issues/78#event-433832369>.
> 

-- 
Daniel Gomes
Gestor do Arquivo.pt, Área de Serviços Avançados
Head of Arquivo.pt - the Portuguese Web Archive, Advanced Services
Department

Fundação para Ciência e a Tecnologia
Unidade FCCN - Computação Científica Nacional
Av. do Brasil, 101, 1700-066 Lisboa, Portugal
T: [+351] 300 005 190
daniel.gomes@fccn.pt   |   www.fccn.pt

**Comment by Fernando-Melo** [comment]
We are getting different results when searching in arquivo.pt using the textbox and when using opensearch.

http://arquivo.pt/opensearch?query=fccn.pt    --> returns 294 versions for the url
http://arquivo.pt/search.jsp?l=pt&query=fccn.pt&btnSubmit=Pesquisar&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2014  --> returns 441 versions for the url

**Comment by dcgomes** [comment]
I can only see 5 versions on the open search results at http://arquivo.pt/opensearch?query=fccn.pt and not 294.

**Comment by Fernando-Melo** [comment]
<opensearch:totalResults>294</opensearch:totalResults> (total number of versions)
I think it is only displaying part of the results (like only the first page)

**Comment by Fernando-Melo** [comment]
http://arquivo.pt/search.jsp?l=pt&query=http%3A%2F%2Fsapo.pt&btnSubmit=Pesquisar&dateStart=01%2F01%2F1996&dateEnd=31%2F12%2F2014

http://arquivo.pt/nutchwax/opensearch?query=date%3A19960101000000-20141231235959+exacturl%3Ahttp%3A%2F%2Fsapo.pt%2F&hitsPerPage=10000&start=0&dedupField=site&hitsPerDup=10000&hitsPerSite=10000&waybackQuery=true

Both have 1930 versions, It was my problem using exacturl instead of exacturlexpand

**Comment by FCCNhviana** [comment]
It was problems on documentation of opensearch, it was improved already.
