### ISSUE TITLE
Problems with datepicker on advanced page search test

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#831]
**What is the URL that originated the issue?**
1. **Jenkins:**
http://jenkins.arquivo.pt/job/Stage%20-%20m.preprod.arquivo.pt%20-%20Functional%20Testing%20Mobile/lastBuild/pt.arquivo$functional-tests/testReport/pt.fccn.mobile.arquivo.tests.pagesearch/PageAdvancedSearchTest/testPageAdvancedSearch_0_/

**What happened?**
1. Search for FCCN
2. Then choose Advanced Search
3. Change the datepickers (e.g., Datepicker End whith 1 Jun 2018).
4. Click on button search.
5. Then the datepicker appears incorrect.

This problem appears on Android 6 emulator and Android 8 emulator.

**Screenshots**
1. Change the datepicker on advanced search:
![21](https://user-images.githubusercontent.com/25795364/76632259-d6888080-653a-11ea-87e8-ed0df8bd57b4.JPG)
2.  The datepicker on the homepage:
![22](https://user-images.githubusercontent.com/25795364/76632261-d8524400-653a-11ea-98b3-c1996420c028.JPG)

**Comment by igobranco** [comment]
After analyzing the history of that test on continuous integration service, from build 637 until 642. 
Like what is possible to view on the following images:

**image of jenkins table for pt.fccn.mobile.arquivo.tests.pagesearch.PageAdvancedSearchTest**
![image](https://user-images.githubusercontent.com/67018/76867640-b8ce5a80-685d-11ea-8444-940e868d0941.png)

**image of the evolution for  pt.fccn.mobile.arquivo.tests.pagesearch.PageAdvancedSearchTest**
![image](https://user-images.githubusercontent.com/67018/76867660-be2ba500-685d-11ea-8a48-86bdc1802ede.png)

In my opinion this issue isn't related to android, because on some cases also broke on iphone for the same reasons.
On every case the "Current url" value is the same https://m.preprod.arquivo.pt/search.jsp?l=pt&adv_and=fccn&adv_phr=&adv_not=&dateStart=31%2F05%2F2006&dateEnd=01%2F06%2F2018&format=pdf&site=fccn.pt&hitsPerPage=10&btnSubmitBottom=Pesquisar+no+Arquivo

The "Current url" is printed on:
https://github.com/arquivo/functional-tests/blob/c01c5e11f4814ec00215455339540790536ecc05/src/test/java/pt/fccn/mobile/arquivo/tests/pagesearch/PageAdvancedSearchTest.java#L77-L84

I suspect that this could be related to sauce labs, its VMs, or its time zone.

**Comment by igobranco** [comment]
To clarify the error:

Both calendars present a shift of a -1 day, comparing what the user have inserted on advanced search screen and with what is expected to have.

Table that resumes the expected and the error values.
| Type | Expected value | Error value |
| -- | -- | -- |
| start | 2006-05-31 | 2006-05-30 |
| end | 2018-06-01 | 2018-05-31 | 

**Image with THE error**

![image](https://user-images.githubusercontent.com/67018/76870284-698a2900-6861-11ea-82b0-b85f4a5134a6.png)

**Comment by igobranco** [comment]
I think this is related to timezone differences between the server and the client - if the client and server were on current different days.

Currently the dateStart and dateEnd javascript variables were being initialized with time in milliseconds from epoc. I'm going to replace the initialization of those variables with specific year, month and day.

**Comment by igobranco** [comment]
This issue have run ok on last test.

http://jenkins.arquivo.pt/job/Stage%20-%20m.preprod.arquivo.pt%20-%20Functional%20Testing%20Mobile/652/pt.arquivo$functional-tests/testReport/pt.fccn.mobile.arquivo.tests.pagesearch/PageAdvancedSearchTest/
