### ISSUE TITLE
List of versions doesn't consider records produce by warcit

### ISSUE THREAD

**Issue by PedroG1515** [arquivo/pwa-technologies#919]
**What is the URL that originated the issue?**
https://preprod.arquivo.pt/wayback/20021209122700/http://zonanon.org/entrada.html

**What happened?**
The version 20021209122700 doesn't not appear in the list of versions

**Screenshots**
![bug](https://user-images.githubusercontent.com/25795364/81790857-e520f300-94fd-11ea-9e54-1781d999d823.JPG)

**Comment by igobranco** [comment]
It isn't showing because those entries doesn't have any **status**.

It's requesting the CDX API:
https://preprod.arquivo.pt/wayback/cdx?output=json&url=http%3A%2F%2Fzonanon.org%2Fentrada.html&fields=url%2Ctimestamp%2Cstatus&filter=!~status%3A4%7C5&from=19960101&to=20200516

Returns:
```
{"url": "http://zonanon.org/entrada.html", "timestamp": "20021209122700"}
{"url": "http://www.zonanon.org/entrada.html", "timestamp": "20090628204008", "status": "302"}
```

The javascript code needs to always show the entries that doesn't have a **status**.
